// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("backend.Models.Meme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Memes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://i.imgflip.com/1bij.jpg",
                            Title = "Коли дедлайн завтра"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://i.imgflip.com/26am.jpg",
                            Title = "Програміст vs Bug"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://i.imgflip.com/aujac7.jpg",
                            Title = "Meme Board MVP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
